<?php

namespace App\Http\Controllers\Web\User;

use App\Http\Controllers\Controller;
use App\Models\Raw;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UserDashboardController extends Controller
{

    public $user;
    public $dhpl;
    public function __construct(User $user)
    {
        $this->user = $user;
        $this->dhpl = DB::connection('dhpl');
    }
    public function selectUser(Request $request)
    {
        $q = $request->q;
        $users = User::where(function ($query) use ($q) {
            $query->where('email', 'like', '%' . $q . '%');
            $query->orWhere('mobile', 'like', '%' . $q . '%');
        })
            ->where('active', true)

            ->select(['id', 'email', 'mobile'])->take(30)->get();
        if ($users->count()) {
            if ($request->ajax()) {
                return $users;
            }
        }
    }
    public function importData(Request $request)
    {
        $name = [
            "ABIES CAN",
            "ABIES NIG",
            "ABROMA AUG (ULAT KAMBAL)",
            "ABROMA RAD",
            "ABROTANUM",
            "ABSINTHIUM",
            "ACALYPHA IND",
            "ACID ACET",
            "ACID BENZ ",
            "ACID CARB",
            "ACID CHRYSO",
            "ACID LACT",
            "ACID NIT",
            "ACID OXALIC",
            "ACID PHOS",
            "ACID PIC",
            "ACID SALIC",
            "ACID SULP",
            "ACONITE NAP",
            "ACTAEA SPICATA",
            "ADONIS VER ",
            "AEGLE FOLIA",
            "AEGLE MAR (BELSONTH)",
            "AESCULUS HIP",
            "AETHOSA CY",
            "AGARICUS MUSC",
            "AGNUS CAST",
            "ALETRIS FAR",
            "ALFALFA (MEDICAGO SAT)",
            "ALLIUM CEPA",
            "ALLIUM SAT",
            "ALOE SOC",
            "ALSTONIA S.",
            "AMBRA GRISEA",
            "AMLOKI",
            "AMYL NIT",
            "ANACARDIUM OCC",
            "ANACARDIUM ORI",
            "ANAGALLIS ARV",
            "ANTIM CRUD",
            "ANTIM TART",
            "APIS MEL",
            "APOCYNUM AN",
            "APOCYNUM CAN",
            "ARALIA RAC.",
            "ARCTIUM LAPPA",
            "CARDUUS MAR",
            "CARICA PAP",
            "CASCARA SAG",
            "CASSIA SOP",
            "CAULOPHYLLUM T.",
            "CAUSTICUM",
            "CEANOTHUS AM",
            "CEPHALANDRA IND",
            "CHAMOMILLA",
            "CHAPARRO AM",
            "CHELIDONIUM M.",
            "CHENOPODIUM AN",
            "CHIMAPHILA UM",
            "CHINA (CINCHONA OFF)",
            "CHIONANTHUS VIR",
            "CHIRATA",
            "CICUTA V.",
            "CIMICIFUGA R. (ACTAEA RAC)",
            "CINA",
            "CIN MAR SUC",
            "CINNAMONUM (DARUCHINI)",
            "CLEMATIS E.",
            "COCA",
            "COCCULUS IND",
            "COCCUS CACTI",
            "COFFEA CRUD",
            "COLCHICUM A.",
            "COLLINSONIA CAN",
            "COLOCYNTHIS",
            "CONDURANGO",
            "CONIUM MAC ",
            "CONVALLARIA MAJ",
            "COPAIBA OFF",
            "CRATAEGUS OX",
            "CROCUS SAT",
            "CROTON TIG",
            "CUBEBA OFF",
            "CYCLAMEN E. ",
            "DAMIANA (TURNERA D.)",
            "DATURA ARB",
            "DESMODIUM G.",
            "DHANIYA (CORIANDRUM SAT)",
            "DIGITALIS P.",
            "DIOSCOREA V.",
            "DOLICHOS P.",
            "DROSERA R.",
            "DULCAMARA",
            "DURBA ",
            "ECHINACEA AN",
            "ELACH (ELATTARIA C.)",
            "KACHA HALUDA",
            "KALI BICH",
            "KALI IOD",
            "KALMEGH",
            "KALMIA LAT",
            "KAKRA SRINGI (BRUGUIERA G.)",
            "KATPHAL",
            "KREOSOTE (CREOSOTE)",
            "KUR",
            "KURCHI (HOLARRHENA AN)",
            "LABANGA (SYZYGIUM A.)",
            "LACHESIS",
            "LACHNANTHES T",
            "LAPIS ALB",
            "LAPPA MAJ",
            "LATHYRUS SAT",
            "LEDUM PAL",
            "LEMNA MINOR",
            "LIATRIS SPI",
            "LILIUM TIG",
            "LOBELIA IN",
            "LUFFA BINDAL",
            "LYCOPERSICUM E.",
            "LYCOPODIUM C.",
            "MACH RASH",
            "MANJISTHA (CAPPARIS SPINOSA)",
            "MAURI (FOENICULUM VUL)",
            "MELILOTUS ALB",
            "MENTHA PIP",
            "MEZEREUM",
            "MILLEFOLIUM",
            "MITHA BISH (ACONITUM FER)",
            "MULLEIN (VERBASCUM THAP )",
            "MUNDI (SPHAERANTHUS INDICUS)",
            "MYRICA C.",
            "MYRISTICA S.",
            "NIM PATA (AZADIRACHTA IND)",
            "NUPHAR LUT",
            "NUX JUGLANS",
            "NUX MOSCH",
            "NUX VOM",
            "NYCTANTHES ARB",
            "OCIMUM CAN",
            "OCIMUM SAN (TULSI PATA)",
            "OLEUM JEC",
            "ORIGANUM MAJ",
            "ORNITHOGALUM UM",
            "OXYDENDRON ARB",
            "PAEONIA OFF",
            "SPIGELIA ANTH",
            "SPONGIA TOSTA",
            "STAPHYSAGRIA",
            "STRAMONIUM",
            "SULPHUR",
            "SUMBUL",
            "SYMPHYTUM OFF",
            "SYZYGIUM JAM",
            "TABACUM",
            "TEJPATA (CINNAMOMUM T.)",
            "TELLURIUM",
            "TEREBINTHINAE OLE",
            "TERMINALIA C.",
            "TEUCRIUM M. V.",
            "THIOSINAMINUM",
            "THLASPI B. P.",
            "THUJA OCC",
            "TRIBULUS TER",
            "TRILLIUM PEND",
            "URANIUM NIT",
            "URTICA URENS",
            "USTILAGO M.",
            "UVA URSI",
            "VALERIANA OFF",
            "VERATRUM ALB",
            "VERATRUM VIR",
            "VESICARIA COM",
            "VIBURNUM OPU",
            "VIBURNUM PRU",
            "VINCA MINOR",
            "VIOLA ODO",
            "VISCUM ALB",
            "YASTHIMADHU (GLYCYRRHIZA G.)",
            "XANTHOXYLUM F.",
            "YERBA SANTA",
            "YOHIMBINUM",
            "ZINGIBER OFF (ADA SONTH)",
            "ARCTIUM LAPPA",
            "ARGENT NIT",
            "ARJUNA (TERMINALIA ARJUNA)",
            "ARNICA MONT",
            "ARNICA RED",
            "ARS ALB",
            "ARTEMISIA VUL",
            "ARUM TRI",
            "ASAFOETIDA (HING)",
            "ASHWAGANDHA (WITHANIA SOM)",
            "ASPARAGUS OFF",
            "ASPIDOSPERMA",
            "ATISTA IND",
            "ATISTA RAD",
            "AVENA SAT",
            "AZADIRACHTA IND (NIM CHAL)",
            "BABCHI  (PSORALEA COR)",
            "BABLA GAM (ACACIA ARABICA)",
            "BADIAGA",
            "BAHERA",
            "BALSAMUM PERU",
            "BAPTISIA TINC",
            "BELLADONNA ",
            "BELLIS PER",
            "BERBERIS AQU",
            "BERBERIS VUL",
            "BLATTA ORI",
            "BLUMEA ODO",
            "BOERHAAVIA DIF",
            "BOERHAAVIA REP",
            "BORAX",
            "BOVISTA",
            "BRAHMI",
            "BRIHATI (SOLANUM IND)",
            "BRYONIA ALB",
            "BRYOPHYLLUM",
            "BUFO RANA",
            "CACTUS G.",
            "CALADIUM SEG",
            "CALENDULA OFF",
            "CALENDULA SUC",
            "CALOTROPIS G.",
            "CAMPHORA",
            "CANTHARIS",
            "CAPSICUM A.",
            "ELATERIUM",
            "EMBELIA RIB",
            "EPHEDRA NEB",
            "EQUISETUM HY",
            "EUCALYPTUS G.",
            "EUPATORIUM PER",
            "EUPATORIUM PUR",
            "EUPHORBIA HY",
            "EUPHRASIA OFF",
            "FILIX MAS",
            "FORMICA RUFA",
            "FRAXINUS AM",
            "FUCUS VESI",
            "GALEGA OFF",
            "GAMBOGIA",
            "GAULTHERIA PRO",
            "GELSEMIUM S.",
            "GENTIANA LUT",
            "GERANIUM MAC",
            "GINSENG",
            "GLONOINUM",
            "GOL MARIC",
            "GOSSYPIUM H.",
            "GRANATUM",
            "GRINDELIA R.",
            "GUAIACUM",
            "GUGUL",
            "GYMNEMA SYL",
            "HAMAMELIS V.",
            "HARITAKI",
            "HELLEBORUS NIG",
            "HELONIAS D.",
            "HYDRASTIS CAN",
            "HYDROCOTYLE A.",
            "HYGROPHILLA S.",
            "HYOSCYAMUS NIG",
            "HYPERICUM P.",
            "IBERIS AMARA",
            "IGNATIA AMARA",
            "IODIUM",
            "IPECAC",
            "IRIS VER",
            "JABORANDI",
            "JALAPA",
            "JANOSIA ASHOKA (ASHOK)",
            "JATROPHA C.",
            "JAIN (TRACYSPERMUM AMMI)",
            "JIRA (CUMINUM CYMINUM)",
            "JUSTICIA ADHA (VASAKA)",
            "KACHA PAPA",
            "PASSIFLORA INC",
            "PATAL PATA (TRICHOSANTHES D.)",
            "PATHARKUCHI (BRYOPHYLLUM C.)",
            "PETROLEUM",
            "PHOSPHORUS",
            "PHYSOSTIGMA V.",
            "PHYTOLACCAC DEC",
            "PINUS LAM",
            "PIPER MET",
            "PIPUL (FICUS R.)",
            "PLANTAGO MAJ",
            "PODOPHYLLUM P.",
            "PULSATILLA NIG",
            "QUASSIA AMARA",
            "RANUNCULUS A.",
            "RAPHANUS SAT",
            "RATANHIA",
            "RAUWOLFIA SER",
            "RHEUM",
            "RHODODENDRON C.",
            "RHUS AROM",
            "RHUS TOX",
            "RHUS VEN",
            "RICINUS COM",
            "ROBINIA P.",
            "ROHITAKA",
            "RUMEX C.",
            "RUTA G.",
            "SABADILLA",
            "SABAL SERRU",
            "SABINA",
            "SALIX NIG",
            "SAMBUCUS NIG",
            "SANGUINARIA CAN",
            "SANGUINARINUM NIT",
            "SARRACENIA P.",
            "SARSAPARILLA",
            "SCROPHULARIA NOD",
            "SECALE COR",
            "SEMUL (BOMBAX CEIBA)",
            "SENECIO AUR",
            "SENEGA",
            "SENNA (SONAPATA)",
            "SEPIA",
            "SHAPLA PHULA (NYMPHAEA ODO)",
            "SHATAMULL (ASPARAGAS RAC)",
            "SHILAJIT",
            "SOLIDAGO V.",
            "SOMRAJ",
        ];
        $unit = [
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "ltr",
            "kg",
            "kg",
            "ltr",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "ltr",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "ltr",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
            "kg",
        ];
        // $name2 =[];
        // $unit2 =[];
        for ($i = 0; $i < count($name); $i++) {
            $raw = new Raw;
            $raw->name = $name[$i];
            $raw->unit = $unit[$i];
            $raw->category_id = 1;
            $raw->active = true;
            $raw->type = 'raw';
            $raw->save();
        }
    }

    public function selectNewProduct(Request $request)
    {

        $users = $this->dhpl->table('ecommerce_products')->where('name', 'like', '%' . $request->q . '%')
            ->orWhere('cat_title', 'like', '%' . $request->q . '%')
            ->select(['id', 'cat_title', 'name','unit'])->take(30)->get();
        if ($users->count()) {
            if ($request->ajax()) {
                // return Response()->json(['items'=>$users]);
                return $users;
            }
        } else {
            if ($request->ajax()) {
                return $users;
            }
        }
    }
}
